// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.
// For example, different possibilities are:

// Colour here:            G G        B G        R G        B R
// Becomes colour here:     G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given 'RRGBRGBB' you should return 'G'.


function triangle(row) {
  prev = '', res = []
  row = row.split('')
  // console.log(row)
  
  while (row.length > 1) {
    for (i = 0; i < row.length; i++) {
      // console.log(row[i], prev)  
      prev == row[i] ? res.push(prev) : 
      prev == 'R' && row[i] == 'G' ? res.push('B') :
      prev == 'G' && row[i] == 'B' ? res.push('R') :
      prev == 'R' && row[i] == 'B' ? res.push('G') : 
      prev == 'G' && row[i] == 'R' ? res.push('B') : 
      prev == 'B' && row[i] == 'R' ? res.push('G') :
      prev == 'B' && row[i] == 'G' ? res.push('R') : null
      // console.log(res)
      prev = row[i]
    }
    row = res
    res = [], prev = ''
    // console.log('new row', row)  
  }
   
  return row[0]
}
